/**
 * End-to-end audio analysis over a real encoded media file.
 *
 * The other audio tests feed the engine hand-built Float32Arrays. This one
 * starts from an actual 16-bit WAV on disk — generated by
 * `scripts/make-fixture-media.mjs`, whose structure is documented there — and
 * runs the whole audio path over it.
 *
 * That distinction matters: it exercises decoding, sample scaling, and the
 * detectors' interaction over a multi-second signal with a real noise floor,
 * rather than over an idealized buffer.
 *
 * The fixture is synthesised rather than sampled from a film: the repository
 * must contain no copyrighted media, and a synthetic signal lets the
 * assertions be exact.
 */

import { readFileSync } from 'node:fs';
import { fileURLToPath } from 'node:url';
import { describe, expect, it } from 'vitest';
import { detectSpeechRegions } from '@/audio/vad';
import { SpeakerDiarizer } from '@/audio/diarization';
import { SoundEventDetector } from '@/audio/soundEvents';
import { findSilences } from '@/audio/silence';
import { buildScreenplay } from '@/core/pipeline';
import { createIdFactory } from '@/utils/id';
import type { EvidenceEvent, SilenceEvidence, SoundEvidence, SpeakerEvidence } from '@/evidence/types';

const FIXTURE = fileURLToPath(new URL('./fixtures/fixture-speech.wav', import.meta.url));

/** Minimal 16-bit PCM WAV reader — enough for the fixture, and no dependency. */
function readWav(path: string): { samples: Float32Array; sampleRate: number } {
  const buffer = readFileSync(path);
  expect(buffer.toString('ascii', 0, 4)).toBe('RIFF');
  expect(buffer.toString('ascii', 8, 12)).toBe('WAVE');

  const sampleRate = buffer.readUInt32LE(24);
  const bitsPerSample = buffer.readUInt16LE(34);
  expect(bitsPerSample).toBe(16);

  // Walk the chunk list rather than assuming `data` starts at byte 44.
  let offset = 12;
  while (offset < buffer.length - 8) {
    const id = buffer.toString('ascii', offset, offset + 4);
    const size = buffer.readUInt32LE(offset + 4);
    if (id === 'data') {
      const count = Math.floor(size / 2);
      const samples = new Float32Array(count);
      for (let i = 0; i < count; i++) samples[i] = buffer.readInt16LE(offset + 8 + i * 2) / 32768;
      return { samples, sampleRate };
    }
    offset += 8 + size + (size % 2);
  }
  throw new Error('No data chunk found in WAV');
}

const { samples, sampleRate } = readWav(FIXTURE);
const nextId = createIdFactory('fx');
const secondsOf = (ms: number) => ms / 1000;

describe('audio analysis over a real WAV file', () => {
  it('reads the fixture as 16 kHz mono, about 14 seconds long', () => {
    expect(sampleRate).toBe(16_000);
    expect(samples.length / sampleRate).toBeCloseTo(14, 0);
  });

  it('finds exactly the two utterances the fixture contains', () => {
    const regions = detectSpeechRegions(samples, { sampleRate });
    expect(regions).toHaveLength(2);

    // Voice A occupies 2.0–4.0 s, voice B 8.0–10.0 s.
    expect(secondsOf(regions[0]!.start)).toBeGreaterThan(1.5);
    expect(secondsOf(regions[0]!.start)).toBeLessThan(2.6);
    expect(secondsOf(regions[1]!.start)).toBeGreaterThan(7.5);
    expect(secondsOf(regions[1]!.start)).toBeLessThan(8.6);
  });

  it('does not mistake the percussive burst for speech', () => {
    const regions = detectSpeechRegions(samples, { sampleRate });
    // The impact sits at 10.0–10.15 s; broadband noise must fail the ZCR gate.
    const duringImpact = regions.filter(
      (r) => secondsOf(r.start) > 9.8 && secondsOf(r.start) < 10.4,
    );
    expect(duringImpact).toHaveLength(0);
  });

  it('separates the two voices into two speaker clusters', () => {
    const regions = detectSpeechRegions(samples, { sampleRate });
    const diarizer = new SpeakerDiarizer({ sampleRate });
    const assigned = regions
      .map((region) => {
        const from = Math.floor((region.start / 1000) * sampleRate);
        const to = Math.min(samples.length, Math.ceil((region.end / 1000) * sampleRate));
        return diarizer.assign(samples.subarray(from, to), region.start, region.end);
      })
      .filter((a) => a !== null);

    expect(assigned).toHaveLength(2);
    expect(diarizer.speakerCount).toBe(2);
    expect(assigned[1]!.speakerId).not.toBe(assigned[0]!.speakerId);
    expect(assigned[1]!.turnChange).toBe(true);
  });

  it('detects the percussive burst as a sound event', () => {
    const detector = new SoundEventDetector({ sampleRate });
    const onsets: { timestamp: number }[] = [];
    const chunk = sampleRate * 2;
    for (let offset = 0; offset < samples.length; offset += chunk) {
      const slice = samples.subarray(offset, Math.min(offset + chunk, samples.length));
      onsets.push(...detector.push(slice, Math.round((offset / sampleRate) * 1000)));
    }

    const nearImpact = onsets.filter(
      (o) => secondsOf(o.timestamp) > 9.7 && secondsOf(o.timestamp) < 10.6,
    );
    expect(nearImpact.length).toBeGreaterThanOrEqual(1);
  });

  it('reports the four-second gap between utterances as a significant silence', () => {
    const regions = detectSpeechRegions(samples, { sampleRate });
    const silences = findSilences(regions);
    const significant = silences.filter((s) => s.significant);

    expect(significant).toHaveLength(1);
    expect(secondsOf(significant[0]!.durationMs)).toBeGreaterThan(3);
  });

  it('builds a screenplay carrying the sound and silence beats', () => {
    // The full path the web app takes: audio evidence -> scenes -> screenplay.
    const regions = detectSpeechRegions(samples, { sampleRate });
    const diarizer = new SpeakerDiarizer({ sampleRate });
    const events: EvidenceEvent[] = [];

    for (const region of regions) {
      const from = Math.floor((region.start / 1000) * sampleRate);
      const to = Math.min(samples.length, Math.ceil((region.end / 1000) * sampleRate));
      const assignment = diarizer.assign(samples.subarray(from, to), region.start, region.end);
      if (!assignment) continue;
      const speaker: SpeakerEvidence = {
        id: nextId(),
        source: 'audio-speaker',
        start: assignment.start,
        end: assignment.end,
        confidence: assignment.confidence,
        provisional: false,
        payload: { speakerId: assignment.speakerId },
      };
      events.push(speaker);
    }

    const detector = new SoundEventDetector({ sampleRate });
    for (let offset = 0; offset < samples.length; offset += sampleRate * 2) {
      const slice = samples.subarray(offset, Math.min(offset + sampleRate * 2, samples.length));
      for (const onset of detector.push(slice, Math.round((offset / sampleRate) * 1000))) {
        const sound: SoundEvidence = {
          id: nextId(),
          source: 'audio-event',
          start: onset.timestamp,
          end: onset.timestamp + 250,
          confidence: onset.classified ? 'low' : 'unknown',
          provisional: false,
          payload: { kind: onset.kind },
        };
        events.push(sound);
      }
    }

    for (const gap of findSilences(regions)) {
      if (!gap.significant) continue;
      const silence: SilenceEvidence = {
        id: nextId(),
        source: 'audio-silence',
        start: gap.start,
        end: gap.end,
        confidence: 'medium',
        provisional: false,
        payload: { durationMs: gap.durationMs, significant: true },
      };
      events.push(silence);
    }

    const result = buildScreenplay(events, {
      durationMs: 14_000,
      completeSourceRange: { start: 0, end: 14_000 },
      includeLowConfidence: true,
    });

    const beats = result.scenes.flatMap((s) => s.beats);
    const sounds = beats.filter((b) => b.type === 'sound');
    expect(sounds.length).toBeGreaterThan(0);
    expect(sounds.some((b) => b.type === 'sound' && /silence|pause/i.test(b.description))).toBe(true);

    // No dialogue: speaker clusters alone are not words, and nothing may
    // fabricate lines from the fact that someone spoke.
    expect(beats.filter((b) => b.type === 'dialogue')).toHaveLength(0);
    expect(result.coverage.ratio).toBe(1);
  });
});
