/**
 * Fountain export.
 *
 * Fountain is plain-text screenplay markup that Final Draft, Highland, Slugline
 * and others import directly, which makes it the most useful export FrameScript
 * can produce.
 *
 * Every document carries a header stating that this is a *reconstruction from
 * observed playback*, not a production screenplay. That statement is not
 * optional decoration — it is the difference between an honest artifact and a
 * forgery of someone's shooting script.
 */

import { formatTimecode } from '../../utils/time';
import { describeSources } from '../../evidence/provenance';
import type { ScreenplayDocument, ScreenplayLine } from '../types';

export interface ExportMetadata {
  title?: string;
  seriesTitle?: string;
  season?: number;
  episode?: number;
  platform?: 'youtube' | 'netflix';
  contentId?: string;
  generatedAt?: number;
  /** Coverage summary lines, produced by `coverageNote`. */
  coverage?: string[];
}

export interface FountainOptions {
  includeTimestamps?: boolean;
  includeConfidence?: boolean;
  includeEvidenceRefs?: boolean;
  /** Emit the secondary language beneath each dialogue line. */
  dualLanguage?: boolean;
}

const DISCLAIMER = [
  'This document was reconstructed by FrameScript from observable playback evidence',
  '(subtitles, audio, picture, on-screen text, playback timing and user corrections).',
  'It is NOT an original, shooting, or production screenplay, and it is not a transcript',
  'supplied by the streaming service. Descriptions and scene headings are inferred and',
  'may be wrong or incomplete.',
];

export function toFountain(
  document: ScreenplayDocument,
  metadata: ExportMetadata = {},
  options: FountainOptions = {},
): string {
  const out: string[] = [];

  // --- Title page ---
  const title = buildTitle(metadata);
  out.push(`Title: ${title}`);
  if (metadata.seriesTitle) out.push(`Series: ${metadata.seriesTitle}`);
  if (metadata.platform) out.push(`Source: ${platformLabel(metadata.platform)}`);
  out.push(`Language: ${document.language}`);
  out.push('Generated By: FrameScript (reconstructed screenplay)');
  if (metadata.generatedAt) out.push(`Date: ${new Date(metadata.generatedAt).toISOString().slice(0, 10)}`);
  out.push('');

  // Fountain treats `=` lines as synopses, which every reader renders as notes.
  for (const line of DISCLAIMER) out.push(`= ${line}`);
  out.push('');

  if (metadata.coverage?.length) {
    for (const line of metadata.coverage) out.push(`= ${line}`);
    out.push('');
  }

  // --- Body ---
  for (const line of document.lines) {
    out.push(...renderLine(line, options));
  }

  return `${out.join('\n').replace(/\n{3,}/g, '\n\n').trim()}\n`;
}

function renderLine(line: ScreenplayLine, options: FountainOptions): string[] {
  const out: string[] = [];
  const note = buildNote(line, options);

  switch (line.kind) {
    case 'scene-heading':
      out.push('');
      // A forced scene heading; without the `.` Fountain guesses from the text,
      // and localized headings ("실내.") do not match its English heuristics.
      out.push(`.${line.text}`);
      if (note) out.push(note);
      out.push('');
      break;

    case 'character':
      out.push('');
      out.push(line.text.toUpperCase());
      break;

    case 'dialogue':
      out.push(line.text);
      if (options.dualLanguage && line.secondaryText) out.push(line.secondaryText);
      if (note) out.push(note);
      out.push('');
      break;

    case 'transition':
      out.push('');
      out.push(`> ${line.text}`);
      out.push('');
      break;

    case 'on-screen-text':
    case 'sound':
    case 'action':
      out.push(line.text);
      if (note) out.push(note);
      out.push('');
      break;
  }
  return out;
}

/** Fountain inline note `[[ ... ]]`, used for timestamps and provenance. */
function buildNote(line: ScreenplayLine, options: FountainOptions): string | null {
  const parts: string[] = [];
  if (options.includeTimestamps) parts.push(formatTimecode(line.start, { millis: true }));
  if (options.includeConfidence && line.confidence) parts.push(line.confidence);
  if (line.origin === 'ai-translation') parts.push('AI translation');
  else if (line.origin === 'audio-asr') parts.push('audio transcription');
  if (line.fallbackLanguage) parts.push(`shown in ${line.fallbackLanguage}`);
  if (options.includeEvidenceRefs && line.provenance) {
    parts.push(describeSources(line.provenance.sources));
    if (line.provenance.inferred) parts.push('inferred');
  }
  return parts.length > 0 ? `[[${parts.join(' | ')}]]` : null;
}

function buildTitle(metadata: ExportMetadata): string {
  if (metadata.seriesTitle && metadata.season !== undefined && metadata.episode !== undefined) {
    const code = `S${String(metadata.season).padStart(2, '0')}E${String(metadata.episode).padStart(2, '0')}`;
    return metadata.title ? `${metadata.seriesTitle} ${code} — ${metadata.title}` : `${metadata.seriesTitle} ${code}`;
  }
  return metadata.title ?? 'Untitled';
}

function platformLabel(platform: 'youtube' | 'netflix'): string {
  return platform === 'youtube' ? 'YouTube' : 'Netflix';
}
