/**
 * Subtitle normalization.
 *
 * Caption containers are not a clean event stream. A single spoken line can
 * arrive as dozens of DOM mutations: YouTube's automatic captions grow word by
 * word, both platforms re-render identical text on every animation frame, and
 * styling spans fragment the same sentence across nested nodes.
 *
 * This module turns that noise into one cue per utterance. It is pure and
 * synchronous so every case below is a unit test rather than a YouTube session.
 *
 * One rule throughout: normalization may fix *rendering artefacts*. It never
 * rewrites what a character said.
 */

import { collapseWhitespace, comparableText, isProgressiveExtension, stripInvisible } from '../../utils/text';
import type { MediaTimeMs } from '../../utils/time';

export interface RawSubtitleObservation {
  /** Text as read from the DOM, possibly multi-line. */
  text: string;
  /** Player currentTime when the text was observed. */
  mediaTime: MediaTimeMs;
  language: string;
  autoGenerated?: boolean;
}

export interface NormalizedCue {
  text: string;
  /** Original visual lines, preserved: `- A` / `- B` means two speakers. */
  lines: string[];
  start: MediaTimeMs;
  end: MediaTimeMs;
  language: string;
  autoGenerated: boolean;
  /** Raw text of the last observation that contributed, for the Evidence view. */
  raw: string;
  /** True when the cue was assembled from progressive (growing) observations. */
  progressive: boolean;
}

/**
 * Cleans one observation's text.
 *
 * Zero-width characters, non-breaking spaces and per-line whitespace runs are
 * rendering artefacts and are removed. Line structure survives, because caption
 * line breaks carry meaning (speaker dashes, sung lyrics).
 */
export function normalizeSubtitleText(input: string): { text: string; lines: string[] } {
  const lines = stripInvisible(input)
    .replace(/\r\n?/g, '\n')
    .split('\n')
    .map((line) => collapseWhitespace(line))
    .filter((line) => line.length > 0);

  return { text: lines.join(' '), lines };
}

/** Longest suffix of `previous` that is also a prefix of `next`, in words. */
export function rollUpOverlap(previous: string, next: string): number {
  const prevWords = comparableText(previous).split(' ').filter(Boolean);
  const nextWords = comparableText(next).split(' ').filter(Boolean);
  const max = Math.min(prevWords.length, nextWords.length);

  for (let size = max; size > 0; size--) {
    const suffix = prevWords.slice(prevWords.length - size).join(' ');
    const prefix = nextWords.slice(0, size).join(' ');
    if (suffix === prefix) return size;
  }
  return 0;
}

export interface AccumulatorOptions {
  /**
   * A cue is closed if no observation arrives for this long. Guards against a
   * caption container that stops mutating without clearing itself.
   */
  idleTimeoutMs?: number;
  /** Grace added to the end time, approximating display persistence. */
  displayGraceMs?: number;
  /** Cues shorter than this are almost always render flicker. */
  minDurationMs?: number;
  /** Word overlap ratio above which an observation reads as a roll-up. */
  rollUpRatio?: number;
}

const ACC_DEFAULTS: Required<AccumulatorOptions> = {
  idleTimeoutMs: 4_000,
  displayGraceMs: 250,
  minDurationMs: 120,
  rollUpRatio: 0.4,
};

interface PendingCue {
  text: string;
  lines: string[];
  raw: string;
  start: MediaTimeMs;
  lastSeen: MediaTimeMs;
  language: string;
  autoGenerated: boolean;
  progressive: boolean;
}

/**
 * Accumulates raw observations into finalized cues.
 *
 * Feed every observation, including empty ones (which signal the caption
 * cleared). Each call returns cues that completed as a result.
 */
export class SubtitleAccumulator {
  #options: Required<AccumulatorOptions>;
  #pending: PendingCue | null = null;

  constructor(options: AccumulatorOptions = {}) {
    this.#options = { ...ACC_DEFAULTS, ...options };
  }

  get hasPending(): boolean {
    return this.#pending !== null;
  }

  observe(observation: RawSubtitleObservation): NormalizedCue[] {
    const { text, lines } = normalizeSubtitleText(observation.text);
    const emitted: NormalizedCue[] = [];
    const pending = this.#pending;

    // Empty observation: the caption cleared, so any pending cue is complete.
    if (text.length === 0) {
      const closed = this.#finalize(observation.mediaTime);
      if (closed) emitted.push(closed);
      return emitted;
    }

    if (!pending) {
      this.#pending = this.#open(observation, text, lines);
      return emitted;
    }

    // Language changed mid-cue: two tracks, two cues.
    if (pending.language !== observation.language) {
      const closed = this.#finalize(observation.mediaTime);
      if (closed) emitted.push(closed);
      this.#pending = this.#open(observation, text, lines);
      return emitted;
    }

    // Idle for too long: the previous cue ended without a clearing event.
    if (observation.mediaTime - pending.lastSeen > this.#options.idleTimeoutMs) {
      const closed = this.#finalize(pending.lastSeen);
      if (closed) emitted.push(closed);
      this.#pending = this.#open(observation, text, lines);
      return emitted;
    }

    // Identical re-render: extend, do not duplicate.
    if (comparableText(pending.text) === comparableText(text)) {
      pending.lastSeen = observation.mediaTime;
      pending.raw = observation.text;
      return emitted;
    }

    // Progressive caption: "I don't" -> "I don't think we should go."
    if (isProgressiveExtension(pending.text, text)) {
      pending.text = text;
      pending.lines = lines;
      pending.raw = observation.text;
      pending.lastSeen = observation.mediaTime;
      pending.progressive = true;
      return emitted;
    }

    // Roll-up captions: the display scrolls, so the new text starts with the
    // tail of the old. Close the old cue and keep only the genuinely new words.
    const overlapWords = rollUpOverlap(pending.text, text);
    const nextWordCount = text.split(/\s+/).filter(Boolean).length;
    if (overlapWords > 0 && nextWordCount > 0 && overlapWords / nextWordCount >= this.#options.rollUpRatio) {
      const closed = this.#finalize(observation.mediaTime);
      if (closed) emitted.push(closed);
      const remainder = text.split(/\s+/).slice(overlapWords).join(' ');
      if (remainder.length > 0) {
        this.#pending = this.#open(observation, remainder, [remainder]);
        this.#pending.progressive = true;
      }
      return emitted;
    }

    // Unrelated text: a new cue.
    const closed = this.#finalize(observation.mediaTime);
    if (closed) emitted.push(closed);
    this.#pending = this.#open(observation, text, lines);
    return emitted;
  }

  /** Closes any pending cue. Call on pause, seek, track change or stop. */
  flush(at?: MediaTimeMs): NormalizedCue | null {
    return this.#finalize(at ?? this.#pending?.lastSeen ?? 0);
  }

  reset(): void {
    this.#pending = null;
  }

  #open(observation: RawSubtitleObservation, text: string, lines: string[]): PendingCue {
    return {
      text,
      lines,
      raw: observation.text,
      start: observation.mediaTime,
      lastSeen: observation.mediaTime,
      language: observation.language,
      autoGenerated: observation.autoGenerated ?? false,
      progressive: false,
    };
  }

  #finalize(endTime: MediaTimeMs): NormalizedCue | null {
    const pending = this.#pending;
    this.#pending = null;
    if (!pending || pending.text.length === 0) return null;

    const end = Math.max(endTime, pending.lastSeen) + this.#options.displayGraceMs;
    if (end - pending.start < this.#options.minDurationMs) return null;

    return {
      text: pending.text,
      lines: pending.lines,
      start: pending.start,
      end,
      language: pending.language,
      autoGenerated: pending.autoGenerated,
      raw: pending.raw,
      progressive: pending.progressive,
    };
  }
}

/**
 * Splits a cue into dialogue lines when the caption uses speaker dashes.
 * `- Where are you?` / `- Here.` is two people, not one long sentence.
 */
export function splitDashedLines(lines: readonly string[]): string[] {
  const dashed = lines.filter((line) => /^[-–—]\s*/.test(line));
  if (dashed.length < 2) return [lines.join(' ')].filter((l) => l.length > 0);
  return lines.map((line) => line.replace(/^[-–—]\s*/, '').trim()).filter(Boolean);
}
