/**
 * Subtitle file parsing (SRT and WebVTT).
 *
 * The extension reads subtitles from a live player's DOM. Everything else —
 * the web app, the CLI, the MCP server — starts from a file the user already
 * has. This parser is the shared entry point for that path.
 *
 * It is deliberately forgiving about the things real subtitle files get wrong
 * (BOM, CRLF, missing indices, `.` instead of `,` in SRT timestamps, stray
 * blank lines) and deliberately strict about never inventing content: a cue
 * whose timing cannot be parsed is skipped and counted, not guessed at.
 */

import { createIdFactory } from '../../utils/id';
import type { MediaTimeMs } from '../../utils/time';
import type { SubtitleEvidence } from '../../evidence/types';
import { normalizeSubtitleText } from './normalize';

export interface ParsedCue {
  index: number;
  start: MediaTimeMs;
  end: MediaTimeMs;
  text: string;
  lines: string[];
}

export interface ParseSubtitleResult {
  format: 'srt' | 'vtt' | 'unknown';
  cues: ParsedCue[];
  /** Blocks that could not be parsed. Reported, never silently dropped. */
  skipped: number;
  /** Non-fatal problems worth showing the user. */
  warnings: string[];
}

/** `00:01:02,345` (SRT) or `00:01:02.345` / `01:02.345` (VTT). */
const TIMESTAMP = /(?:(\d{1,3}):)?(\d{1,2}):(\d{1,2})[,.](\d{1,3})/;
const CUE_TIMING = new RegExp(`^\\s*${TIMESTAMP.source}\\s*-->\\s*${TIMESTAMP.source}`);

export function parseTimestamp(input: string): MediaTimeMs | null {
  const match = TIMESTAMP.exec(input.trim());
  if (!match) return null;
  const [, hours, minutes, seconds, millis] = match;
  const ms = Number(millis?.padEnd(3, '0') ?? 0);
  return (
    Number(hours ?? 0) * 3_600_000 + Number(minutes) * 60_000 + Number(seconds) * 1_000 + ms
  );
}

/**
 * Detects the format from the file's own header rather than its extension,
 * because a `.txt` holding WebVTT is common and an extension is not evidence.
 */
export function detectSubtitleFormat(content: string): ParseSubtitleResult['format'] {
  const head = content.replace(/^\uFEFF/, '').trimStart();
  if (/^WEBVTT/i.test(head)) return 'vtt';
  if (CUE_TIMING.test(head) || /^\d+\s*\r?\n\s*\d{1,3}:\d{2}/.test(head)) return 'srt';
  return 'unknown';
}

export function parseSubtitleFile(content: string): ParseSubtitleResult {
  const format = detectSubtitleFormat(content);
  const warnings: string[] = [];

  const normalized = content
    .replace(/^\uFEFF/, '')
    .replace(/\r\n?/g, '\n')
    // WebVTT NOTE and STYLE blocks are metadata, not dialogue.
    .replace(/^(?:NOTE|STYLE|REGION)[\s\S]*?(?=\n\n|$)/gm, '');

  const blocks = normalized.split(/\n{2,}/);
  const cues: ParsedCue[] = [];
  let skipped = 0;

  for (const block of blocks) {
    const lines = block.split('\n').filter((line) => line.trim().length > 0);
    if (lines.length === 0) continue;
    if (/^WEBVTT/i.test(lines[0]!)) continue;

    const timingIndex = lines.findIndex((line) => CUE_TIMING.test(line));
    if (timingIndex < 0) {
      // A block with text but no timing is unusable — count it rather than
      // attaching the text to a neighbouring cue's timing.
      if (lines.some((line) => /\S/.test(line))) skipped++;
      continue;
    }

    const timingLine = lines[timingIndex]!;
    const [startRaw, endRaw] = timingLine.split('-->');
    const start = parseTimestamp(startRaw ?? '');
    const end = parseTimestamp(endRaw ?? '');
    if (start === null || end === null) {
      skipped++;
      continue;
    }

    const textLines = lines.slice(timingIndex + 1);
    const { text, lines: cleanLines } = normalizeSubtitleText(textLines.join('\n'));
    if (text.length === 0) {
      skipped++;
      continue;
    }

    if (end <= start) {
      warnings.push(`Cue at ${startRaw?.trim()} ends before it starts; using a 2s duration.`);
    }

    cues.push({
      index: cues.length + 1,
      start,
      end: end > start ? end : start + 2_000,
      text,
      lines: cleanLines,
    });
  }

  if (cues.length === 0 && skipped > 0) {
    warnings.push('No cues could be read. The file may not be SRT or WebVTT.');
  }
  if (skipped > 0) {
    warnings.push(`${skipped} block${skipped === 1 ? '' : 's'} skipped as unparseable.`);
  }

  // Files occasionally arrive out of order; the timeline assumes media order.
  cues.sort((a, b) => a.start - b.start);
  return { format, cues, skipped, warnings };
}

/**
 * Converts parsed cues into subtitle evidence.
 *
 * `autoGenerated` matters downstream: an authored track is treated as stronger
 * evidence than a machine transcription, so the caller must say which this is
 * rather than letting the parser assume.
 */
export function cuesToEvidence(
  cues: readonly ParsedCue[],
  options: { language: string; autoGenerated?: boolean; idPrefix?: string },
): SubtitleEvidence[] {
  const nextId = createIdFactory(options.idPrefix ?? 'file-sub');
  return cues.map((cue) => ({
    id: nextId(),
    source: 'subtitle' as const,
    start: cue.start,
    end: cue.end,
    confidence: options.autoGenerated ? ('medium' as const) : ('high' as const),
    provisional: false,
    payload: {
      text: cue.text,
      language: options.language,
      ...(options.autoGenerated ? { autoGenerated: true } : {}),
    },
  }));
}

/**
 * Guesses a language from a filename such as `movie.ko.srt` or `movie_en.vtt`.
 * Returns `und` when there is no clear marker — never a guess.
 */
export function languageFromFilename(filename: string): string {
  const match = /[._-]([a-z]{2})(?:[-_][A-Za-z]{2,4})?\.(?:srt|vtt|sbv|ass|ssa)$/i.exec(filename);
  return match ? match[1]!.toLowerCase() : 'und';
}
