/**
 * YouTube caption observation.
 *
 * Uses a MutationObserver on the caption container rather than polling: YouTube
 * mutates captions many times a second during automatic (progressive) captions,
 * and polling would either miss words or burn CPU next to 4K playback.
 *
 * Raw observations go straight to `SubtitleAccumulator`, which owns all the
 * normalization logic. This class only reads the DOM.
 */

import { DisposableStore, waitForCondition } from '../../utils/lifecycle';
import { secondsToMs } from '../../utils/time';
import { throttle } from '../../utils/lifecycle';
import type { RawSubtitleObservation } from '../../capture/subtitle/normalize';
import { areCaptionsEnabled, queryAll, queryFirst, YOUTUBE_SELECTORS } from './selectors';

export interface SubtitleObserverOptions {
  root?: ParentNode;
  /** Collapse mutation bursts within this window into one read. */
  throttleMs?: number;
  /** Language reported alongside each observation. */
  language?: string;
  autoGenerated?: boolean;
}

export class YouTubeSubtitleObserver {
  #root: ParentNode;
  #store = new DisposableStore();
  #throttleMs: number;
  #language: string;
  #autoGenerated: boolean;
  #active = false;
  #lastText = '';
  #observationCount = 0;

  constructor(options: SubtitleObserverOptions = {}) {
    this.#root = options.root ?? document;
    this.#throttleMs = options.throttleMs ?? 60;
    this.#language = options.language ?? 'und';
    this.#autoGenerated = options.autoGenerated ?? false;
  }

  get active(): boolean {
    return this.#active;
  }

  get observationCount(): number {
    return this.#observationCount;
  }

  setLanguage(language: string, autoGenerated: boolean): void {
    this.#language = language;
    this.#autoGenerated = autoGenerated;
  }

  /**
   * Starts observing.
   *
   * Resolves once the caption container exists. If captions are off the
   * container never appears; that is reported to the caller as unavailability
   * rather than being retried forever.
   */
  async start(onObservation: (observation: RawSubtitleObservation) => void): Promise<boolean> {
    if (this.#active) return true;

    let container: Element;
    try {
      container = await waitForCondition(
        () => queryFirst(YOUTUBE_SELECTORS.captionWindow, this.#root),
        { timeoutMs: 8_000, pollMs: 250 },
      );
    } catch {
      return false;
    }

    const video = queryFirst<HTMLVideoElement>(YOUTUBE_SELECTORS.video, this.#root);
    const read = throttle(() => {
      const text = this.#readCaptionText();
      // Only emit on change; the container re-renders far more often than the
      // text changes, and the accumulator would otherwise see thousands of
      // identical observations per line.
      if (text === this.#lastText) return;
      this.#lastText = text;
      this.#observationCount++;
      onObservation({
        text,
        mediaTime: video ? secondsToMs(video.currentTime) : 0,
        language: this.#language,
        autoGenerated: this.#autoGenerated,
      });
    }, this.#throttleMs);

    const observer = new MutationObserver(() => read());
    observer.observe(container, { childList: true, subtree: true, characterData: true });
    this.#store.add(() => {
      observer.disconnect();
      read.cancel();
    });

    // The container can exist while empty; an initial read catches a cue that
    // was already on screen when observation started.
    read();
    this.#active = true;
    return true;
  }

  stop(): void {
    this.#store.dispose();
    this.#store = new DisposableStore();
    this.#active = false;
    this.#lastText = '';
  }

  /** True when the player reports captions as enabled. */
  captionsEnabled(): boolean {
    return areCaptionsEnabled(this.#root);
  }

  /**
   * Reads the current caption text.
   *
   * Segments are joined with spaces and lines preserved: YouTube renders each
   * visual line as its own element, and a line break in a caption can mean two
   * speakers.
   */
  #readCaptionText(): string {
    const container = queryFirst(YOUTUBE_SELECTORS.captionWindow, this.#root);
    if (!container) return '';

    const segments = queryAll(YOUTUBE_SELECTORS.captionSegment, container);
    if (segments.length === 0) return (container.textContent ?? '').trim();

    // Group segments by their rendered line so line structure survives.
    const lines = new Map<Element, string[]>();
    for (const segment of segments) {
      const lineNode = segment.closest('.caption-visual-line, .ytp-caption-window-container') ?? segment;
      const bucket = lines.get(lineNode) ?? [];
      bucket.push(segment.textContent ?? '');
      lines.set(lineNode, bucket);
    }
    return [...lines.values()].map((parts) => parts.join('')).join('\n');
  }
}
