/**
 * The evidence data model.
 *
 * Every source — subtitles, audio, video, OCR, playback, metadata, the user —
 * produces `EvidenceEvent`s and nothing else. Nothing writes to the screenplay
 * directly. This is what makes provenance possible: each rendered line can be
 * traced back to the exact events that justify it.
 *
 * All timestamps are media time in milliseconds (see utils/time.ts).
 */

import type { MediaTimeMs } from '../utils/time';

export type ConfidenceLevel = 'high' | 'medium' | 'low' | 'unknown';

export type EvidenceSourceId =
  | 'subtitle'
  | 'audio-asr'
  | 'audio-speaker'
  | 'audio-event'
  | 'audio-silence'
  | 'video'
  | 'ocr'
  | 'playback'
  | 'metadata'
  | 'user';

export interface EvidenceEventBase {
  id: string;
  source: EvidenceSourceId;
  start: MediaTimeMs;
  end?: MediaTimeMs;
  confidence: ConfidenceLevel;
  /**
   * True while more evidence could still revise this event. Provisional events
   * are shown in the UI but are not finalized into a saved screenplay.
   */
  provisional: boolean;
}

// --- Source-specific payloads -------------------------------------------------

export interface SubtitleEvidence extends EvidenceEventBase {
  source: 'subtitle';
  payload: {
    text: string;
    /** BCP-47-ish language id as reported by the platform, e.g. `en`, `ko`. */
    language: string;
    /** Speaker name when the subtitle track itself labels one ("JANE: ..."). */
    speakerLabel?: string;
    /** Bracketed non-speech captions, e.g. "[door slams]". */
    nonSpeech?: boolean;
    /** True for platform auto-generated (ASR) caption tracks. */
    autoGenerated?: boolean;
    /** Raw text before normalization, kept for the Evidence view. */
    raw?: string;
  };
}

export interface SpeechEvidence extends EvidenceEventBase {
  source: 'audio-asr';
  payload: {
    text: string;
    language?: string;
    speakerId?: string;
    /** Provider-reported score, when the provider supplies a calibrated one. */
    providerScore?: number;
  };
}

export interface SpeakerEvidence extends EvidenceEventBase {
  source: 'audio-speaker';
  payload: {
    /** Anonymous cluster identity, e.g. `speaker-001`. Never an actor name. */
    speakerId: string;
    /** Cosine distance to the cluster centroid at assignment time. */
    distance?: number;
    /** True when this event marks a change of speaker from the previous one. */
    turnChange?: boolean;
  };
}

export type SoundEventKind =
  | 'door'
  | 'knock'
  | 'footsteps'
  | 'phone'
  | 'alarm'
  | 'glass'
  | 'impact'
  | 'gunshot'
  | 'vehicle'
  | 'laughter'
  | 'applause'
  | 'music-start'
  | 'music-end'
  | 'music-swell'
  | 'ambience-change'
  | 'unclassified';

export interface SoundEvidence extends EvidenceEventBase {
  source: 'audio-event';
  payload: {
    kind: SoundEventKind;
    /** Peak loudness relative to the recent floor, in dB. */
    prominenceDb?: number;
    /** Free-text descriptor, only ever from a provider that actually heard it. */
    description?: string;
  };
}

export interface SilenceEvidence extends EvidenceEventBase {
  source: 'audio-silence';
  payload: {
    durationMs: number;
    /** True when the silence is long enough to be narratively meaningful. */
    significant: boolean;
  };
}

export type VisualEvidenceKind =
  | 'scene-change'
  | 'character'
  | 'action'
  | 'object'
  | 'setting'
  | 'expression'
  | 'on-screen-text'
  | 'camera-context';

/**
 * A pointer to a frame that was analyzed. Deliberately does **not** carry pixel
 * data: keyframes live in a bounded in-memory cache and are dropped as soon as
 * their window is analyzed. Nothing here can be used to reconstruct media.
 */
export interface EphemeralFrameRef {
  timestamp: MediaTimeMs;
  /** Sequence number from requestVideoFrameCallback, when available. */
  frameSequence?: number;
  /** Analysis-copy dimensions, not playback dimensions. */
  width: number;
  height: number;
}

export interface VisualEvidence extends EvidenceEventBase {
  source: 'video';
  payload: {
    kind: VisualEvidenceKind;
    description?: string;
    /** Ids of characters/visual clusters involved, when known. */
    participantIds?: string[];
    /** Local heuristic metrics that triggered or support this observation. */
    metrics?: TemporalMetrics;
    frameRefs?: EphemeralFrameRef[];
    /** True when a model inferred this rather than a deterministic detector. */
    inferred?: boolean;
    /**
     * Pauses detected inside a sustained action. Recorded because a hesitation
     * mid-gesture is narratively meaningful and is exactly the detail that
     * dense temporal observation exists to catch — the vision layer is told
     * about it so its description can preserve it.
     */
    hesitationCount?: number;
  };
}

export interface OcrEvidence extends EvidenceEventBase {
  source: 'ocr';
  payload: {
    text: string;
    /** Normalized [0,1] box within the analysis frame. */
    region?: { x: number; y: number; width: number; height: number };
    /** True when only a text-*region* was detected and no characters were read. */
    unrecognized?: boolean;
  };
}

export type PlaybackEventKind =
  | 'play'
  | 'pause'
  | 'seek'
  | 'rate-change'
  | 'ended'
  | 'stall'
  | 'resize';

export interface PlaybackEvidence extends EvidenceEventBase {
  source: 'playback';
  payload: {
    kind: PlaybackEventKind;
    /** For seeks: where playback jumped from. */
    fromTime?: MediaTimeMs;
    playbackRate?: number;
    videoWidth?: number;
    videoHeight?: number;
  };
}

export interface MetadataEvidence extends EvidenceEventBase {
  source: 'metadata';
  payload: {
    kind: 'title' | 'series' | 'chapter' | 'duration' | 'content-id';
    value: string;
    /** Chapter/segment name when the platform exposes chapters. */
    chapterTitle?: string;
  };
}

export type UserCorrectionKind =
  | 'speaker-assignment'
  | 'speaker-rename'
  | 'speaker-merge'
  | 'speaker-split'
  | 'setting'
  | 'scene-boundary'
  | 'dialogue-text'
  | 'action-text';

export interface UserEvidence extends EvidenceEventBase {
  source: 'user';
  payload: {
    kind: UserCorrectionKind;
    value: string;
    targetId?: string;
    /** `forward` applies the correction to all later matching evidence too. */
    scope?: 'single' | 'forward' | 'all';
  };
}

export type EvidenceEvent =
  | SubtitleEvidence
  | SpeechEvidence
  | SpeakerEvidence
  | SoundEvidence
  | SilenceEvidence
  | VisualEvidence
  | OcrEvidence
  | PlaybackEvidence
  | MetadataEvidence
  | UserEvidence;

// --- Temporal metrics ---------------------------------------------------------

/**
 * Cheap, local, frame-to-frame measurements produced by the 100 ms scanner.
 *
 * These are heuristic scores in [0,1], **not** probabilities. They are named
 * `*Score` rather than `*Probability` throughout for exactly that reason.
 */
export interface TemporalMetrics {
  frameDifference?: number;
  motionScore?: number;
  sceneCutScore?: number;
  textChangeScore?: number;
  faceChangeScore?: number;
  /** Mean luma in [0,1]; near-zero for the black frames DRM playback yields. */
  luminance?: number;
}

export interface TemporalVisualEvent {
  timestamp: MediaTimeMs;
  frameSequence?: number;
  metrics: TemporalMetrics;
  /** Aggregate salience in [0,1] used to decide what deserves deep analysis. */
  importance: number;
}

// --- Provenance ---------------------------------------------------------------

export interface Provenance {
  evidenceIds: string[];
  sources: EvidenceSourceId[];
  confidence: ConfidenceLevel;
  /** True when a model or heuristic went beyond what a source literally stated. */
  inferred: boolean;
}

// --- Source status ------------------------------------------------------------

export type EvidenceSourceState =
  | 'available'
  | 'starting'
  | 'active'
  | 'unavailable'
  | 'permission-required'
  | 'protected-content'
  | 'unsupported'
  | 'failed';

export interface EvidenceSourceStatus {
  id: EvidenceSourceId;
  state: EvidenceSourceState;
  /** User-facing, already-localized-to-English explanation. Never a stack. */
  message?: string;
  eventCount: number;
  lastEventAt?: MediaTimeMs;
}

export type SourceStateMap = Record<EvidenceSourceId, EvidenceSourceStatus>;

export function createSourceStatus(
  id: EvidenceSourceId,
  state: EvidenceSourceState = 'unavailable',
): EvidenceSourceStatus {
  return { id, state, eventCount: 0 };
}

export const ALL_SOURCE_IDS: readonly EvidenceSourceId[] = [
  'subtitle',
  'audio-asr',
  'audio-speaker',
  'audio-event',
  'audio-silence',
  'video',
  'ocr',
  'playback',
  'metadata',
  'user',
];

export function createSourceStateMap(): SourceStateMap {
  const map = {} as SourceStateMap;
  for (const id of ALL_SOURCE_IDS) map[id] = createSourceStatus(id);
  return map;
}
